AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CustomParameter001:
    Type: "String"
    Description: "This is custom-parameter."
    Default: "hogehogehooge"
  DomainName:
    Type: "String"
    Description: "This is domain name for cloudfront distributoin."
  AcmCertificateArn:
    Type: "String"
  HostedZoneId:
    Type: "String"
  User:
    Type: "String"
  Password:
    Type: "String"

Resources:
  # ------------------------------------------------------------#
  # S3::Bucket
  # ------------------------------------------------------------#
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "s3-${CustomParameter001}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True

    Type: "AWS::CodeStarConnections::Connection"
    Properties:
      ConnectionName: !Sub ""
      ProviderType: "GitHub"
