AWSTemplateFormatVersion: "2010-09-09"
Description: "cdn with authentication"

Parameters:
  SystemCode:
    Type: "String"
  SystemEnv:
    Type: "String"

Resources:
  OAC:
    Type: "AWS::CloudFront::OriginAccessControl"
    Properties: 
      OriginAccessControlConfig:
        Description: Access Control
        Name: !Sub "oac-${SystemCode}-${SystemEnv}"
        OriginAccessControlOriginType: "s3"
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    DependsOn: OAC
    Properties: 
      DistributionConfig:
        Comment: !Sub "cloudfront-${SystemCode}-${SystemEnv}"
        Aliases:
          - { Fn::ImportValue: !Sub "hostedzone-${SystemCode}-${SystemEnv}-name" }
        DefaultRootObject: "index.html"
        DefaultCacheBehavior: 
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: !Sub "s3-${SystemCode}-${SystemEnv}-contents-asset"
          ViewerProtocolPolicy: "redirect-to-https"
        Enabled: true
        Origins:
          - DomainName: !Sub "s3-${SystemCode}-${SystemEnv}-contents-asset.s3.ap-northeast-1.amazonaws.com"
            Id: !Sub "s3-${SystemCode}-${SystemEnv}-contents-asset"
            OriginAccessControlId: !GetAtt OAC.Id
            S3OriginConfig: 
              OriginAccessIdentity: ""
        PriceClass: "PriceClass_All"
        ViewerCertificate:
          AcmCertificateArn: { Fn::ImportValue: !Sub "acm-${SystemCode}-${SystemEnv}-arn" }
          SslSupportMethod: "sni-only"
        CustomErrorResponses:
          - ErrorCode: 404
            ResponsePagePath: /404.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0
          - ErrorCode: 403
            ResponsePagePath: /404.html
            ResponseCode: 200
            ErrorCachingMinTTL: 0

  S3BucketPolicyContentsAsset:
      Type: "AWS::S3::BucketPolicy"
      Properties:
        Bucket: !Sub "s3-${SystemCode}-${SystemEnv}-contents-asset"
        PolicyDocument: 
          Version: "2012-10-17"
          Statement: 
            - Sid: "AllowCloudFrontServicePrincipal"
              Effect: "Allow"
              Principal: 
                Service: 
                  - "cloudfront.amazonaws.com"
              Action: 
                - "s3:GetObject"
              Resource: 
                - !Sub "arn:aws:s3:::s3-${SystemCode}-${SystemEnv}-contents-asset/*"
              Condition: 
                StringEquals:
                  AWS:SourceArn: 
                    - !Join 
                      - ""
                      - - !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/"
                        - !Ref CloudFrontDistribution

  DnsRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Name: { Fn::ImportValue: !Sub "hostedzone-${SystemCode}-${SystemEnv}-name" }
      Type: A
      HostedZoneId: { Fn::ImportValue: !Sub "hostedzone-${SystemCode}-${SystemEnv}-id" }
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2 # this is AWS-specific constant value

