AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  CustomParameter001:
    Type: "String"
    Description: "This is custom-parameter."
    Default: "custom001"
  GitHubOrganizationName:
    Type: "String"
    Default: "custom001"

Resources:
  # ------------------------------------------------------------#
  # CodeStarConnections::Connection
  # ------------------------------------------------------------#
  ConnectionGitHub:
    Type: "AWS::CodeStarConnections::Connection"
    Properties:
      ConnectionName: !Sub "git-${GitHubOrganizationName}-${CustomParameter001}"
      ProviderType: "GitHub"

Outputs:
  ConnectionGitHub:
    Value: !Ref ConnectionGitHub
    Export:
      Name: !Sub "git-${GitHubOrganizationName}-${CustomParameter001}"
