AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  SystemCode:
    Type: "String"
  SystemEnv:
    Type: "String"

Resources:
  ConnectionGitHub:
    Type: "AWS::CodeStarConnections::Connection"
    Properties:
      ConnectionName: !Sub "git-${SystemCode}-${SystemEnv}"
      ProviderType: "GitHub"

Outputs:
  ConnectionGitHub:
    Value: !Ref ConnectionGitHub
    Export:
      Name: !Sub "git-${SystemCode}-${SystemEnv}"
  ConnectionGitHubArn:
    Value: !GetAtt ConnectionGitHub.ConnectionArn
    Export:
      Name: !Sub "git-${SystemCode}-${SystemEnv}-arn"
