AWSTemplateFormatVersion: "2010-09-09"
Description: "Cognito with ParameterStore"

Parameters:
  SystemCode:
    Type: "String"
  SystemEnv:
    Type: "String"

Resources:
  CognitoUserPool:
    Type: "AWS::Cognito::UserPool"
    Properties:
      UserPoolName: !Sub "cgnt-${SystemCode}-${SystemEnv}-user-pool"

  CognitoUserPoolDomain:
    Type: "AWS::Cognito::UserPoolDomain"
    Properties:
      Domain: !Sub "cgnt-${SystemCode}-${SystemEnv}-user-pool-domain"
      UserPoolId: !Ref CognitoUserPool

  CognitoUserPoolClient:
    Type: "AWS::Cognito::UserPoolClient"
    Properties:
      ClientName: !Sub "cgnt-${SystemCode}-${SystemEnv}-client"
      UserPoolId: !Ref CognitoUserPool
      CallbackURLs:
        - !Join 
          - ""
          - - "https://"
            - { Fn::ImportValue: !Sub "hostedzone-${SystemCode}-${SystemEnv}-name" }
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - code
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - openid


Outputs:
  CognitoUserPoolId:
    Value: !Ref CognitoUserPool
    Export:
      Name: !Sub "cgnt-${SystemCode}-${SystemEnv}-user-pool-id"
  CognitoUserPoolAppId:
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: !Sub "cgnt-${SystemCode}-${SystemEnv}-user-pool-app-id"
  CognitoUserPoolDomain:
    Value: !Sub "${CognitoUserPoolDomain}.auth.${AWS::Region}.amazoncognito.com"
    Export:
      Name: !Sub "cgnt-${SystemCode}-${SystemEnv}-user-pool-domain"
